name: Build and Push My Docker Image to AWS ECS

on:
  push:
    branches:
      - main  # Change to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: us-east-1  # Change to your AWS region

    - name: Build Docker Image
      run: |
        docker build -t mike .
        
    - name: Tag Docker Image
      run: |
        docker tag mike:latest 339712843199.dkr.ecr.us-east-1.amazonaws.com/marck-repo:latest
        # Replace `339712843199` and `marck-repo` with your account ID and ECR repository name

    - name: Push Docker Image to Amazon ECR
      run: |
        docker push 339712843199.dkr.ecr.us-east-1.amazonaws.com/marck-repo:latest

